from multi_label_pigeon import multi_label_annotate
from IPython.display import display, Image

annotations = multi_label_annotate(
  ['1_3.jpg', '2_3.jpg','3_3.jpg'],
  options={'Lengkap/Tidak':['Lengkap = Kecenderungan ekshibisionis, merasa mampu diterima secara sosial, keter-gantungan sosial.','Tidak = Depresif, tidak mengakui kenyataan, tertekan secraa neurotis, kurang dorongan berprestasi'], 
           'sedih/gembira':['Perasaan sedih /tertekan','Bersemangat dan motivasi berprestasi'],
           'lokasi':[
                      'Atas = Kurang kuat pegangan, kurang mantap, berfantasi untuk nampak kuat. Mungkin takabur atau tak mau tahu, mungkin optimis terhadap kerjanya, memandang rendah terhadap orang lain, tendensi kurang yakin akan dirinya.',
                     'tengah = Memiliki adaptasi yang cukup baik, bersifat egosentris, insecure dan rigid, berusaha kontrol secara cermat.',
                     'bawah = 	Perasaan insecure dan tak pasti, berpikir  pada hal-hal konkrit/ berpijak pada realita. Kebutuhan akan kepastian/depresif, kurang usaha, mudah menyerah, di dominasi oleh asadar, kebutuhan keseimbangan, kontrol, menunjukkan keseimbangan, ketenangan kestabilan (secara demonstratif)',
                     'kanan = Kontrol emosionil, berusaha keras untuk sukses, orientasi lingkungan/dunia luar, ekstrofert, orientasi masa yang akan datang',
                     'kananAtas = Negativisme pada diri sendiri, agresif, memberontak.',
                     'kiri = Dikuasai emosi, menekankan masa yang lalu, tendensi impulsif, self oriented, depresif tapi banyak frustasi, introfert, bayak dikendalikan ketaksadaran',
                     'bawahKiri = Dikuasai emosi, menekankan masa lalu, tendensi impulsif, self-oriented, intro-vert, banyak dikendalikan ketidaksa-daran, depresif'
                     ],
          'Garis':[
                  'konsisten = Penyesuaian diri baik',
		              'kabur = Kurang berani tampil dan menyatakan diri, cemas, insecure, ragu, takut, tidak pasti, kontrol yang rigid yang didasari oleh rasa tertekan dan kurang mampu berkarya, depresif, kurang mampu dan kurang gairah, intelektual dan introversive, spirituil',
                  'Tebal = Penuntut, menguasai, menentang keku-asaan, dorongan bermusuhan, yakin diri, anxiety, tegang, kerusakan otak organis, manic',
                  'Tipis = Ada hambatan berhubungan dengan lingkungan, biasa nampak pada tendebsi skizoid',
                  'TekananUbah = Tak stabil, impulsif, mudah frustasi, histeris atao siklotomik',
                  'TipisPatahTidakTetap = Ketakutan, tidak aman, tidak pasti',
                  'keriting, patah berulangdisertai tekanan ringan=Tendensi skizoid alkoholik',
                  'gergaji = Kecemasan, kontrol motorik, rendah, kurang dapat mencapai keseimbangan',
                  'DariGarisDasar = Perasaan tak aman, ingin diakui kelompoknya',
                  'KoordinasiJelek = Tegangan yang muncul, cemas, mungkin kerusakan otak',
                  'TebalKotorShadingBanyak = Adalah hal biasa untuk anak kecil, anxiety neurotics, psikotis',
                  'GambarSketsa = anxiety, tidak tetap, insecure',
                  ],
          ' KEPALA':[
                          'TakLengkap = Tendensi hambatan dalam hubungan sosial, neourotis',
                          'Agakbesar = Ada kemungkinan gangguan organis (misalnya, orang sering sakit, kerusakan otak, kemunduran, tendensi hipokondriasis, intelegensi kurang, pikirannya melayang (over) pada paranoid, terlalu membanggakan intelek, penekanan pada fantasi (pada anak-anak) aspirasi intelektuil (mungkin disertai orandiosity), kurang masak dalam instropeksi atau fantasi, simptom-simptom pada kepala',
                          'TerlaluBesar = Tendensi aspirasi lebih besar dari pada kemampuan' ,
                          'DiGambarDiAkhir = Konflik dalam hubungan manusiawi, mungkin ada kesulitan bicara',
                          'Kabur/TakJelas = Kesadaran pribadi , keraguan shy',
                          'KepalaBesarJKLain = Opposite sex regarded as smarter or as possesing greater social authority',
                          'BentukKurangTepat = Organicity ',
                          'AAneh/Ganjil = Identifikasi feminin berhubungan dengan narcisistik dan obsesif kompulasif',
                          ],
       ' RAMBUT ':[
                          'Botak',
                          'MenekankanRambut',
                          'PerhatianBerlebihan',
                          'Acak2an',
                          'RambutPadaBagianTengah',
                          'DiUlang2',
                          'RambutPutihPadaPria',
                          'RambutWanitaYgTakAdadiPria',
                          'PenempatanTepat',
                          'RambutTipis',
                          'RambutMenyolokDanKacau',
                          'Gundul/SedikitSekali',
                          'RambutGondrong',
                          'Jambang/Kumis/rambutLain',
                          'RambutPadaRahang',
                          'JenggotKambing',
                          'Jenggot/JambangDitekankan',
                          ],
		 ' asdasdasd ':['Perasaan sedih /tertekan',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          '',
                          ],				  },
  display_fn=lambda filename: display(Image(filename))
)